/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Hari (https://sketchfab.com/Hari31)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/2019-chevrolet-corvette-c8-stingray-790c40ccff6843eab0b7b4bd18421ff8
title: 2019 Chevrolet Corvette C8 Stingray
*/

import { useDonutStore } from "store/PhysicsStore";
import {
	CloseCar,
	ColorFade,
	ConvertibleDown,
	ConvertibleUp,
	MakeBloomLights,
	OpenCar,
} from "lib/Utils";

import { useEffect, useLayoutEffect, useRef } from "react";

import { useGLTF } from "@react-three/drei";
import { Color, MeshPhongMaterial } from "three";
import { useThree } from "@react-three/fiber";

export function Corvette(props) {
	const { open, openRoof, color } = useDonutStore();

	const frunk = useRef();
	const leftIndicator = useRef();
	const taillights = useRef();
	const angledTailLights = useRef();
	const tailLightsRef = useRef();
	const dayLights = useRef();
	const frontRim = useRef();
	const rightDoor = useRef();
	const leftDoor = useRef();
	const midTrunk = useRef();
	const model = useRef();
	const roof = useRef();
	const roofInterior = useRef();
	const rightDoorGlass = useRef();
	const leftDoorGlass = useRef();

	const { scene } = useThree();

	useEffect(() => {
		const refs = [
			leftIndicator,
			taillights,
			dayLights,
			angledTailLights,
			tailLightsRef,
			frontRim,
		];

		MakeBloomLights(refs);

		scene.traverse((nodes) => {
			if (nodes.isMesh && nodes.name.length === 0) {
				nodes.material.envMapIntensity = 0.5;
				nodes.castShadow = true;
			} else if (nodes.isMesh && nodes.name.length > 0) {
				nodes.material.envMapIntensity = 1.2;
				nodes.material.roughness = 0.8;
				nodes.material.metalness = 0.8;
			}
		});

		ColorFade(roof, color);
	}, [color]);

	const viewport = useThree((state) => state.viewport);

	useLayoutEffect(() => {
		if (open === false) {
			CloseCar(frunk, rightDoor, leftDoor, midTrunk);
		} else if (open === true) {
			OpenCar(frunk, rightDoor, leftDoor, midTrunk);
		}

		if (openRoof === false) {
			ConvertibleDown(roof, roofInterior, rightDoorGlass, leftDoorGlass);
		} else if (openRoof === true) {
			ConvertibleUp(roof, roofInterior, rightDoorGlass, leftDoorGlass);
		}
	}, [open, openRoof]);

	const { nodes, materials } = useGLTF(
		"./models/2019_chevrolet_corvette_c8_stingray.glb",
	);

	return (
		<group ref={model} {...props} dispose={null}>
			<group name="Sketchfab_Scene">
				<group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
					<group
						name="298f46dca4dd4cf3a1125065f2b92ae1fbx"
						rotation={[Math.PI / 2, 0, 0]}
						scale={0.009}
					>
						<group name="RootNode">
							<group
								name="Main_Chassis"
								position={[0, 71, 0]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<group name="Corvette_Badge">
									<mesh
										castShadow
										name="Corvette_Badge_Badges_0"
										geometry={
											nodes.Corvette_Badge_Badges_0
												.geometry
										}
										material={materials.Badges}
									/>
								</group>
								<group name="Headlights_Housing">
									<group name="Day_Lights">
										<mesh
											castShadow
											ref={dayLights}
											name="Day_Lights_Day_Lights_0"
											geometry={
												nodes.Day_Lights_Day_Lights_0
													.geometry
											}
											material={materials.Day_Lights}
										/>
									</group>
									<group name="Headlights">
										<Headlights />

										<mesh
											castShadow
											name="Headlights_Headlights_0"
											geometry={
												nodes.Headlights_Headlights_0
													.geometry
											}
											material={materials.Headlights}
										/>
									</group>
									<group name="turnlight_r">
										<mesh
											castShadow
											ref={taillights}
											name="turnlight_r_Right_Indicator_0"
											geometry={
												nodes
													.turnlight_r_Right_Indicator_0
													.geometry
											}
											material={materials.Right_Indicator}
										/>
									</group>
									<group name="Right_Indicator">
										<mesh
											castShadow
											ref={leftIndicator}
											name="Right_Indicator_Left_Indicator_0"
											geometry={
												nodes
													.Right_Indicator_Left_Indicator_0
													.geometry
											}
											material={materials.Left_Indicator}
										/>
									</group>
									<group name="Taillights">
										<mesh
											castShadow
											ref={angledTailLights}
											name="Taillights_Taillights_0"
											geometry={
												nodes.Taillights_Taillights_0
													.geometry
											}
											material={materials.Taillights}
										/>
									</group>
									<group name="Reverse_Lights">
										<mesh
											castShadow
											ref={tailLightsRef}
											name="Reverse_Lights_Reverse_Lights_0"
											geometry={
												nodes
													.Reverse_Lights_Reverse_Lights_0
													.geometry
											}
											material={materials.Reverse_Lights}
										/>
									</group>
									<group name="Brake_Lights">
										<mesh
											castShadow
											name="Brake_Lights_Brake_Lights_0"
											geometry={
												nodes
													.Brake_Lights_Brake_Lights_0
													.geometry
											}
											material={materials.Brake_Lights}
										/>
									</group>
									<group name="License_Plate_Lights">
										<mesh
											castShadow
											name="License_Plate_Lights_License_Plate_Lights_0"
											geometry={
												nodes
													.License_Plate_Lights_License_Plate_Lights_0
													.geometry
											}
											material={
												materials.License_Plate_Lights
											}
										/>
									</group>
									<mesh
										castShadow
										name="Headlights_Housing_Lights_0"
										geometry={
											nodes.Headlights_Housing_Lights_0
												.geometry
										}
										material={materials.Lights}
									/>
								</group>
								<group name="SUSpension">
									<mesh
										castShadow
										name="SUSpension_Misc_0"
										geometry={
											nodes.SUSpension_Misc_0.geometry
										}
										material={materials.Misc}
									/>
								</group>
								<group name="Roof">
									<mesh
										ref={roof}
										castShadow
										name="Roof_Body_Color_0"
										geometry={
											nodes.Roof_Body_Color_0.geometry
										}
										material={materials.Body_Color}
										// material-color={new Color()

										// 	.setRGB(color.r, color.g, color.b)
										// 	.convertSRGBToLinear()}
										// 0.70980392157, 0.21176470588, 0.26666666667
										// 353, 55, 46
										// blue : 60, 100 53
										// red : 0, 100, 50
									/>
									<mesh
										ref={roofInterior}
										castShadow
										name="Roof_Interior_0"
										geometry={
											nodes.Roof_Interior_0.geometry
										}
										//ROOFINT
										material={materials.Interior}
									/>
								</group>
								<group name="62L_LT2_V8_Engine_and_Engine_Bay">
									<group name="Engine_Bay_Bolts">
										<mesh
											castShadow
											name="Engine_Bay_Bolts_Engine_Decals_0"
											geometry={
												nodes
													.Engine_Bay_Bolts_Engine_Decals_0
													.geometry
											}
											material={materials.Engine_Decals}
										/>
									</group>
									<group name="Grille1">
										<mesh
											castShadow
											name="Grille1_Black_0"
											geometry={
												nodes.Grille1_Black_0.geometry
											}
											material={materials.Black}
										/>
										<mesh
											castShadow
											name="Grille1_Grille_3_0"
											geometry={
												nodes.Grille1_Grille_3_0
													.geometry
											}
											material={materials.Grille_3}
										/>
										<mesh
											castShadow
											name="Grille1_Grille_1_0"
											geometry={
												nodes.Grille1_Grille_1_0
													.geometry
											}
											material={materials.Grille_1}
										/>
									</group>
									<group name="Carbon_FIber">
										<mesh
											castShadow
											name="Carbon_FIber_Carbon_Fiber_0"
											geometry={
												nodes
													.Carbon_FIber_Carbon_Fiber_0
													.geometry
											}
											material={materials.Carbon_Fiber}
										/>
									</group>
									<mesh
										castShadow
										name="62L_LT2_V8_Engine_and_Engine_Bay_Engine_Cover_0"
										geometry={
											nodes[
												"62L_LT2_V8_Engine_and_Engine_Bay_Engine_Cover_0"
											].geometry
										}
										material={materials.Engine_Cover}
									/>
									<mesh
										castShadow
										name="62L_LT2_V8_Engine_and_Engine_Bay_Chrome_Engine_Pipes_Use_Grill_5_as_BW_to_Bump_to_Normal_0"
										geometry={
											nodes[
												"62L_LT2_V8_Engine_and_Engine_Bay_Chrome_Engine_Pipes_Use_Grill_5_as_BW_to_Bump_to_Normal_0"
											].geometry
										}
										material={
											materials.Chrome_Engine_Pipes_Use_Grill_5_as_BW_to_Bump_to_Normal
										}
									/>
									<mesh
										castShadow
										name="62L_LT2_V8_Engine_and_Engine_Bay_Engine_Decals_0"
										geometry={
											nodes[
												"62L_LT2_V8_Engine_and_Engine_Bay_Engine_Decals_0"
											].geometry
										}
										material={materials.Engine_Decals}
									/>
								</group>
								<group name="Interior">
									<group name="Interior_Stitches">
										<mesh
											castShadow
											name="Interior_Stitches_Interior_0"
											geometry={
												nodes
													.Interior_Stitches_Interior_0
													.geometry
											}
											material={materials.Interior}
										/>
									</group>
									<group name="Interior_Digitals">
										<mesh
											castShadow
											name="Interior_Digitals_Interior_Buttons_0"
											geometry={
												nodes
													.Interior_Digitals_Interior_Buttons_0
													.geometry
											}
											material={
												materials.Interior_Buttons
											}
										/>
										<mesh
											castShadow
											name="Interior_Digitals_Interior_Display_0"
											geometry={
												nodes
													.Interior_Digitals_Interior_Display_0
													.geometry
											}
											material={
												materials.Interior_Display
											}
										/>
										<mesh
											castShadow
											name="Interior_Digitals_Gauges_0"
											geometry={
												nodes.Interior_Digitals_Gauges_0
													.geometry
											}
											material={materials.Gauges}
										/>
									</group>
									<group name="Interior_Trim">
										<mesh
											castShadow
											name="Interior_Trim_Badges_0"
											geometry={
												nodes.Interior_Trim_Badges_0
													.geometry
											}
											material={materials.Badges}
										/>
										<mesh
											castShadow
											name="Interior_Trim_Interior_Trim_0"
											geometry={
												nodes
													.Interior_Trim_Interior_Trim_0
													.geometry
											}
											material={materials.Interior_Trim}
										/>
									</group>
									<mesh
										castShadow
										name="Interior_Black_0"
										geometry={
											nodes.Interior_Black_0.geometry
										}
										material={materials.Black}
									/>
									<mesh
										castShadow
										name="Interior_Interior_Aluminium_0"
										geometry={
											nodes.Interior_Interior_Aluminium_0
												.geometry
										}
										material={materials.Interior_Aluminium}
									/>
									<mesh
										castShadow
										name="Interior_Plastic_0"
										geometry={
											nodes.Interior_Plastic_0.geometry
										}
										material={materials.Plastic}
									/>
									<mesh
										castShadow
										name="Interior_Grill_4_Speakers_0"
										geometry={
											nodes.Interior_Grill_4_Speakers_0
												.geometry
										}
										material={materials.Grill_4_Speakers}
									/>
									<mesh
										castShadow
										name="Interior_Carpet_0"
										geometry={
											nodes.Interior_Carpet_0.geometry
										}
										material={materials.Carpet}
									/>
									<mesh
										castShadow
										name="Interior_Engine_Decals_0"
										geometry={
											nodes.Interior_Engine_Decals_0
												.geometry
										}
										material={materials.Engine_Decals}
									/>
									<mesh
										castShadow
										name="Interior_Interior_0"
										geometry={
											nodes.Interior_Interior_0.geometry
										}
										material={materials.Interior}
									/>
									<mesh
										castShadow
										name="Interior_Seats_Adjust_the_leather_texture_using_Color_Ramp_or_using_HSV_0"
										geometry={
											nodes
												.Interior_Seats_Adjust_the_leather_texture_using_Color_Ramp_or_using_HSV_0
												.geometry
										}
										material={
											materials.Seats_Adjust_the_leather_texture_using_Color_Ramp_or_using_HSV
										}
									/>
								</group>
								<mesh
									castShadow
									name="Main_Chassis_Body_Color_0"
									geometry={
										nodes.Main_Chassis_Body_Color_0.geometry
									}
									material={materials.Body_Color}
								/>
								<mesh
									castShadow
									name="Main_Chassis_Black_0"
									geometry={
										nodes.Main_Chassis_Black_0.geometry
									}
									material={materials.Black}
								/>
								<mesh
									castShadow
									name="Main_Chassis_Plastic_0"
									geometry={
										nodes.Main_Chassis_Plastic_0.geometry
									}
									material={materials.Plastic}
								/>
								<mesh
									castShadow
									name="Main_Chassis_Invisible_Unimportant_Black_0"
									geometry={
										nodes
											.Main_Chassis_Invisible_Unimportant_Black_0
											.geometry
									}
									material={
										materials.Invisible_Unimportant_Black
									}
								/>
								<mesh
									castShadow
									name="Main_Chassis_Chrome_0"
									geometry={
										nodes.Main_Chassis_Chrome_0.geometry
									}
									material={materials.Chrome}
								/>
								<mesh
									castShadow
									name="Main_Chassis_Painted_Black_0"
									geometry={
										nodes.Main_Chassis_Painted_Black_0
											.geometry
									}
									material={materials.Painted_Black}
								/>
								<mesh
									castShadow
									name="Main_Chassis_Mirror_0"
									geometry={
										nodes.Main_Chassis_Mirror_0.geometry
									}
									material={materials.Mirror}
								/>
								<mesh
									castShadow
									name="Main_Chassis_Grille_6_0"
									geometry={
										nodes.Main_Chassis_Grille_6_0.geometry
									}
									material={materials.Grille_6}
								/>
								<mesh
									castShadow
									name="Main_Chassis_Grille_7_0"
									geometry={
										nodes.Main_Chassis_Grille_7_0.geometry
									}
									material={materials.Grille_7}
								/>
								<mesh
									castShadow
									name="Main_Chassis_Misc_0"
									geometry={
										nodes.Main_Chassis_Misc_0.geometry
									}
									material={materials.Misc}
								/>
							</group>
							<group
								ref={frunk}
								name="Frunk"
								position={[-0.01, 89.11, -117.94]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									castShadow
									name="Frunk_Body_Color_0"
									geometry={nodes.Frunk_Body_Color_0.geometry}
									material={materials.Body_Color}
								/>
								<mesh
									castShadow
									name="Frunk_Plastic_0"
									geometry={nodes.Frunk_Plastic_0.geometry}
									material={materials.Plastic}
								/>
								<mesh
									castShadow
									name="Frunk_Bolt_2_Interior_0"
									geometry={
										nodes.Frunk_Bolt_2_Interior_0.geometry
									}
									material={materials.Bolt_2_Interior}
								/>
							</group>
							<group
								name="Glasses"
								position={[0, 107.66, -32.53]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									castShadow
									name="Glasses_Windshield_0"
									geometry={
										nodes.Glasses_Windshield_0.geometry
									}
									material={materials.Windshield}
								/>
								<mesh
									castShadow
									name="Glasses_Other_Glasses_than_Windshield_0"
									geometry={
										nodes
											.Glasses_Other_Glasses_than_Windshield_0
											.geometry
									}
									material={
										materials.Other_Glasses_than_Windshield
									}
								/>
							</group>
							<group
								name="Front_Right_Wheel"
								position={[93.3, 37.4, -144.8]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									castShadow
									name="Front_Right_Wheel_Painted_Black_0"
									geometry={
										nodes.Front_Right_Wheel_Painted_Black_0
											.geometry
									}
									material={materials.Painted_Black}
								/>
								<mesh
									castShadow
									name="Front_Right_Wheel_Brake_Disc_0"
									geometry={
										nodes.Front_Right_Wheel_Brake_Disc_0
											.geometry
									}
									material={materials.Brake_Disc}
								/>
								<mesh
									castShadow
									name="Front_Right_Wheel_Tire_Treads_0"
									geometry={
										nodes.Front_Right_Wheel_Tire_Treads_0
											.geometry
									}
									material={materials.Tire_Treads}
								/>
								<mesh
									castShadow
									ref={frontRim}
									name="Front_Right_Wheel_Rim_0"
									geometry={
										nodes.Front_Right_Wheel_Rim_0.geometry
									}
									material={materials.material}
								/>
								<mesh
									castShadow
									name="Front_Right_Wheel_Tire_Sidewall_0"
									geometry={
										nodes.Front_Right_Wheel_Tire_Sidewall_0
											.geometry
									}
									material={materials.Tire_Sidewall}
								/>
							</group>
							<group
								name="Front_Right_Brake_Caliper"
								position={[93.3, 37.4, -144.8]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									castShadow
									name="Front_Right_Brake_Caliper_Misc_2_0"
									geometry={
										nodes.Front_Right_Brake_Caliper_Misc_2_0
											.geometry
									}
									material={materials.Misc_2}
								/>
							</group>
							<group
								name="Front_Left_Brake_Caliper"
								position={[-93.3, 37.5, -144.7]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									castShadow
									name="Front_Left_Brake_Caliper_Misc_2_0"
									geometry={
										nodes.Front_Left_Brake_Caliper_Misc_2_0
											.geometry
									}
									material={materials.Misc_2}
								/>
							</group>
							<group
								name="Front_Left_Wheel"
								position={[-93.3, 37.4, -144.8]}
								rotation={[-Math.PI / 2, 0, -Math.PI]}
								scale={100}
							>
								<mesh
									castShadow
									name="Front_Left_Wheel_Painted_Black_0"
									geometry={
										nodes.Front_Left_Wheel_Painted_Black_0
											.geometry
									}
									material={materials.Painted_Black}
								/>
								<mesh
									castShadow
									name="Front_Left_Wheel_Brake_Disc_0"
									geometry={
										nodes.Front_Left_Wheel_Brake_Disc_0
											.geometry
									}
									material={materials.Brake_Disc}
								/>
								<mesh
									castShadow
									name="Front_Left_Wheel_Tire_Treads_0"
									geometry={
										nodes.Front_Left_Wheel_Tire_Treads_0
											.geometry
									}
									material={materials.Tire_Treads}
								/>
								<mesh
									castShadow
									name="Front_Left_Wheel_Rim_0"
									geometry={
										nodes.Front_Left_Wheel_Rim_0.geometry
									}
									material={materials.material}
								/>
								<mesh
									castShadow
									name="Front_Left_Wheel_Tire_Sidewall_0"
									geometry={
										nodes.Front_Left_Wheel_Tire_Sidewall_0
											.geometry
									}
									material={materials.Tire_Sidewall}
								/>
							</group>
							<group
								name="Rear_Right_Wheel"
								position={[93, 39.25, 163.33]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={[100, 105, 105]}
							>
								<mesh
									castShadow
									name="Rear_Right_Wheel_Painted_Black_0"
									geometry={
										nodes.Rear_Right_Wheel_Painted_Black_0
											.geometry
									}
									material={materials.Painted_Black}
								/>
								<mesh
									castShadow
									name="Rear_Right_Wheel_Brake_Disc_0"
									geometry={
										nodes.Rear_Right_Wheel_Brake_Disc_0
											.geometry
									}
									material={materials.Brake_Disc}
								/>
								<mesh
									castShadow
									name="Rear_Right_Wheel_Tire_Treads_0"
									geometry={
										nodes.Rear_Right_Wheel_Tire_Treads_0
											.geometry
									}
									material={materials.Tire_Treads}
								/>
								<mesh
									castShadow
									name="Rear_Right_Wheel_Rim_0"
									geometry={
										nodes.Rear_Right_Wheel_Rim_0.geometry
									}
									material={materials.material}
								/>
								<mesh
									castShadow
									name="Rear_Right_Wheel_Tire_Sidewall_0"
									geometry={
										nodes.Rear_Right_Wheel_Tire_Sidewall_0
											.geometry
									}
									material={materials.Tire_Sidewall}
								/>
							</group>
							<group
								name="Rear_Left_Wheel"
								position={[-93, 39.14, 163.22]}
								rotation={[-Math.PI / 2, 0, -Math.PI]}
								scale={[100, 105, 105]}
							>
								<mesh
									castShadow
									name="Rear_Left_Wheel_Painted_Black_0"
									geometry={
										nodes.Rear_Left_Wheel_Painted_Black_0
											.geometry
									}
									material={materials.Painted_Black}
								/>
								<mesh
									castShadow
									name="Rear_Left_Wheel_Brake_Disc_0"
									geometry={
										nodes.Rear_Left_Wheel_Brake_Disc_0
											.geometry
									}
									material={materials.Brake_Disc}
								/>
								<mesh
									castShadow
									name="Rear_Left_Wheel_Tire_Treads_0"
									geometry={
										nodes.Rear_Left_Wheel_Tire_Treads_0
											.geometry
									}
									material={materials.Tire_Treads}
								/>
								<mesh
									castShadow
									name="Rear_Left_Wheel_Rim_0"
									geometry={
										nodes.Rear_Left_Wheel_Rim_0.geometry
									}
									material={materials.material}
								/>
								<mesh
									castShadow
									name="Rear_Left_Wheel_Tire_Sidewall_0"
									geometry={
										nodes.Rear_Left_Wheel_Tire_Sidewall_0
											.geometry
									}
									material={materials.Tire_Sidewall}
								/>
							</group>
							<group
								name="Right_Door"
								position={[96.28, 60.5, -86.52]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
								ref={rightDoor}
							>
								<group name="Right_Door_Glass">
									<mesh
										ref={rightDoorGlass}
										castShadow
										name="Right_Door_Glass_Other_Glasses_than_Windshield_0"
										geometry={
											nodes
												.Right_Door_Glass_Other_Glasses_than_Windshield_0
												.geometry
										}
										material={
											materials.Other_Glasses_than_Windshield
										}
									/>
								</group>
								<group name="Right_Door_Stitches">
									<mesh
										castShadow
										name="Right_Door_Stitches_Interior_0"
										geometry={
											nodes.Right_Door_Stitches_Interior_0
												.geometry
										}
										material={materials.Interior}
									/>
								</group>
								<group name="Right_Indicator_Mirror">
									<mesh
										castShadow
										name="Right_Indicator_Mirror_Right_Indicator_0"
										geometry={
											nodes
												.Right_Indicator_Mirror_Right_Indicator_0
												.geometry
										}
										material={materials.Right_Indicator}
									/>
								</group>
								<mesh
									castShadow
									name="Right_Door_Body_Color_0"
									geometry={
										nodes.Right_Door_Body_Color_0.geometry
									}
									material={materials.Body_Color}
								/>
								<mesh
									castShadow
									name="Right_Door_Black_0"
									geometry={nodes.Right_Door_Black_0.geometry}
									material={materials.Black}
								/>
								<mesh
									castShadow
									name="Right_Door_Plastic_0"
									geometry={
										nodes.Right_Door_Plastic_0.geometry
									}
									material={materials.Plastic}
								/>
								<mesh
									castShadow
									name="Right_Door_Aluminium_0"
									geometry={
										nodes.Right_Door_Aluminium_0.geometry
									}
									material={materials.Aluminium}
								/>
								<mesh
									castShadow
									name="Right_Door_Painted_Black_0"
									geometry={
										nodes.Right_Door_Painted_Black_0
											.geometry
									}
									material={materials.Painted_Black}
								/>
								<mesh
									castShadow
									name="Right_Door_Mirror_0"
									geometry={
										nodes.Right_Door_Mirror_0.geometry
									}
									material={materials.Mirror}
								/>
								<mesh
									castShadow
									name="Right_Door_Interior_Trim_2_0"
									geometry={
										nodes.Right_Door_Interior_Trim_2_0
											.geometry
									}
									material={materials.Interior_Trim_2}
								/>
								<mesh
									castShadow
									name="Right_Door_Grill_4_Speakers_0"
									geometry={
										nodes.Right_Door_Grill_4_Speakers_0
											.geometry
									}
									material={materials.Grill_4_Speakers}
								/>
								<mesh
									castShadow
									name="Right_Door_Engine_Decals_0"
									geometry={
										nodes.Right_Door_Engine_Decals_0
											.geometry
									}
									material={materials.Engine_Decals}
								/>
								<mesh
									castShadow
									name="Right_Door_Interior_0"
									geometry={
										nodes.Right_Door_Interior_0.geometry
									}
									material={materials.Interior}
								/>
								<mesh
									castShadow
									name="Right_Door_Interior_Buttons_0"
									geometry={
										nodes.Right_Door_Interior_Buttons_0
											.geometry
									}
									material={materials.Interior_Buttons}
								/>
							</group>
							<group
								name="Left_Door"
								position={[-96.2, 60.6, -86.5]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
								ref={leftDoor}
							>
								<group name="Left_Indicator_Mirror">
									<mesh
										castShadow
										name="Left_Indicator_Mirror_Left_Indicator_0"
										geometry={
											nodes
												.Left_Indicator_Mirror_Left_Indicator_0
												.geometry
										}
										material={materials.Left_Indicator}
									/>
								</group>
								<group name="Left_Door_Glass">
									<mesh
										ref={leftDoorGlass}
										castShadow
										name="Left_Door_Glass_Other_Glasses_than_Windshield_0"
										geometry={
											nodes
												.Left_Door_Glass_Other_Glasses_than_Windshield_0
												.geometry
										}
										material={
											materials.Other_Glasses_than_Windshield
										}
									/>
								</group>
								<group name="Left_Door_Stitches">
									<mesh
										castShadow
										name="Left_Door_Stitches_Interior_0"
										geometry={
											nodes.Left_Door_Stitches_Interior_0
												.geometry
										}
										material={materials.Interior}
									/>
								</group>
								<mesh
									castShadow
									name="Left_Door_Body_Color_0"
									geometry={
										nodes.Left_Door_Body_Color_0.geometry
									}
									material={materials.Body_Color}
								/>
								<mesh
									castShadow
									name="Left_Door_Black_0"
									geometry={nodes.Left_Door_Black_0.geometry}
									material={materials.Black}
								/>
								<mesh
									castShadow
									name="Left_Door_Plastic_0"
									geometry={
										nodes.Left_Door_Plastic_0.geometry
									}
									material={materials.Plastic}
								/>
								<mesh
									castShadow
									name="Left_Door_Aluminium_0"
									geometry={
										nodes.Left_Door_Aluminium_0.geometry
									}
									material={materials.Aluminium}
								/>
								<mesh
									castShadow
									name="Left_Door_Painted_Black_0"
									geometry={
										nodes.Left_Door_Painted_Black_0.geometry
									}
									material={materials.Painted_Black}
								/>
								<mesh
									castShadow
									name="Left_Door_Mirror_0"
									geometry={nodes.Left_Door_Mirror_0.geometry}
									material={materials.Mirror}
								/>
								<mesh
									castShadow
									name="Left_Door_Interior_Trim_2_0"
									geometry={
										nodes.Left_Door_Interior_Trim_2_0
											.geometry
									}
									material={materials.Interior_Trim_2}
								/>
								<mesh
									castShadow
									name="Left_Door_Grill_4_Speakers_0"
									geometry={
										nodes.Left_Door_Grill_4_Speakers_0
											.geometry
									}
									material={materials.Grill_4_Speakers}
								/>
								<mesh
									castShadow
									name="Left_Door_Engine_Decals_0"
									geometry={
										nodes.Left_Door_Engine_Decals_0.geometry
									}
									material={materials.Engine_Decals}
								/>
								<mesh
									castShadow
									name="Left_Door_Interior_0"
									geometry={
										nodes.Left_Door_Interior_0.geometry
									}
									material={materials.Interior}
								/>
								<mesh
									castShadow
									name="Left_Door_Interior_Buttons_0"
									geometry={
										nodes.Left_Door_Interior_Buttons_0
											.geometry
									}
									material={materials.Interior_Buttons}
								/>
							</group>
							<group
								name="Trunk_or_Hood"
								position={[0, 126.6, 69.86]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
								ref={midTrunk}
							>
								<group name="Trunk_Glass">
									<mesh
										castShadow
										name="Trunk_Glass_Dark_Engine_View_Glass_0"
										geometry={
											nodes
												.Trunk_Glass_Dark_Engine_View_Glass_0
												.geometry
										}
										material={
											materials.Dark_Engine_View_Glass
										}
									/>
									<mesh
										castShadow
										name="Trunk_Glass_Grille_7_0"
										geometry={
											nodes.Trunk_Glass_Grille_7_0
												.geometry
										}
										material={materials.Grille_7}
									/>
									<mesh
										castShadow
										name="Trunk_Glass_Badges_0"
										geometry={
											nodes.Trunk_Glass_Badges_0.geometry
										}
										material={materials.Badges}
									/>
								</group>
								<mesh
									castShadow
									name="Trunk_or_Hood_Body_Color_0"
									geometry={
										nodes.Trunk_or_Hood_Body_Color_0
											.geometry
									}
									material={materials.Body_Color}
								/>
								<mesh
									castShadow
									name="Trunk_or_Hood_Black_0"
									geometry={
										nodes.Trunk_or_Hood_Black_0.geometry
									}
									material={materials.Black}
								/>
								<mesh
									castShadow
									name="Trunk_or_Hood_Plastic_0"
									geometry={
										nodes.Trunk_or_Hood_Plastic_0.geometry
									}
									material={materials.Plastic}
								/>
							</group>
							<group
								name="Steering_Wheel"
								position={[-40.17, 76.98, -46.4]}
								rotation={[-1.82, 0, 0]}
								scale={100}
							>
								<group name="Steering_Wheel_Decals">
									<mesh
										castShadow
										name="Steering_Wheel_Decals_Interior_0"
										geometry={
											nodes
												.Steering_Wheel_Decals_Interior_0
												.geometry
										}
										material={materials.Interior}
									/>
									<mesh
										castShadow
										name="Steering_Wheel_Decals_Interior_Badge_0"
										geometry={
											nodes
												.Steering_Wheel_Decals_Interior_Badge_0
												.geometry
										}
										material={materials.Interior_Badge}
									/>
								</group>
								<mesh
									castShadow
									name="Steering_Wheel_Black_0"
									geometry={
										nodes.Steering_Wheel_Black_0.geometry
									}
									material={materials.Black}
								/>
								<mesh
									castShadow
									name="Steering_Wheel_Interior_Aluminium_0"
									geometry={
										nodes
											.Steering_Wheel_Interior_Aluminium_0
											.geometry
									}
									material={materials.Interior_Aluminium}
								/>
								<mesh
									castShadow
									name="Steering_Wheel_Interior_0"
									geometry={
										nodes.Steering_Wheel_Interior_0.geometry
									}
									material={materials.Interior}
								/>
							</group>
							<group
								name="Speedo_Needle"
								position={[-40.14, 85.45, -68.47]}
								rotation={[-1.71, 0, 0]}
								scale={100}
							>
								<mesh
									castShadow
									name="Speedo_Needle_Mat_supergt209_0"
									geometry={
										nodes.Speedo_Needle_Mat_supergt209_0
											.geometry
									}
									material={materials["Mat_supergt.209"]}
								/>
							</group>
							<group
								name="Right_WIper"
								position={[-14.41, 83.51, -142.91]}
								rotation={[-0.54, 0, 0]}
								scale={100}
							>
								<mesh
									castShadow
									name="Right_WIper_Black_0"
									geometry={
										nodes.Right_WIper_Black_0.geometry
									}
									material={materials.Black}
								/>
							</group>
							<group
								name="Left_Wiper"
								position={[-72.85, 81.17, -125.06]}
								rotation={[-0.56, 0, 0]}
								scale={100}
							>
								<mesh
									castShadow
									name="Left_Wiper_Black_0"
									geometry={nodes.Left_Wiper_Black_0.geometry}
									material={materials.Black}
								/>
							</group>
							<group
								name="Rear_Left_Brake_Caliper"
								position={[-93, 39.14, 163.22]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									castShadow
									name="Rear_Left_Brake_Caliper_Misc_0"
									geometry={
										nodes.Rear_Left_Brake_Caliper_Misc_0
											.geometry
									}
									material={materials.Misc}
								/>
							</group>
							<group
								name="Rear_Right_Brake_Caliper"
								position={[93, 39.24, 163.32]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									castShadow
									name="Rear_Right_Brake_Caliper_Misc_0"
									geometry={
										nodes.Rear_Right_Brake_Caliper_Misc_0
											.geometry
									}
									material={materials.Misc}
								/>
							</group>
							<group
								name="License_Plate"
								position={[99.48, 70.81, 187.43]}
								rotation={[-Math.PI / 2, 0, 0]}
								scale={100}
							>
								<mesh
									castShadow
									name="License_Plate_Plastic_0"
									geometry={
										nodes.License_Plate_Plastic_0.geometry
									}
									material={materials.Plastic}
								/>
								<mesh
									castShadow
									name="License_Plate_License_Plate_Background_0"
									geometry={
										nodes
											.License_Plate_License_Plate_Background_0
											.geometry
									}
									material={
										materials.License_Plate_Background
									}
								/>
								<mesh
									castShadow
									name="License_Plate_License_Plate_0"
									geometry={
										nodes.License_Plate_License_Plate_0
											.geometry
									}
									material={materials.License_Plate}
								/>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

const material = new MeshPhongMaterial({
	emissive: "white",
	emissiveIntensity: 200,
	color: new Color(100, 100, 100),
	toneMapped: false,
});

function Headlights() {
	const mat = useRef(material);

	return (
		<group>
			<mesh scale={0.025} position={[0.8, 2.015, 0]} material={material}>
				<sphereGeometry />
			</mesh>
			<mesh scale={0.025} position={[-0.8, 2.015, 0]} material={material}>
				<sphereGeometry />
			</mesh>
		</group>
	);
}

useGLTF.preload("./models/2019_chevrolet_corvette_c8_stingray.glb");
