/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/2019_chevrolet_corvette_c8_stingray.glb --transform
Author: Hari (https://sketchfab.com/Hari31)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2019-chevrolet-corvette-c8-stingray-790c40ccff6843eab0b7b4bd18421ff8
Title: 2019 Chevrolet Corvette C8 Stingray
*/

import { useEffect, useRef, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { Color } from "three";

import { useDonutStore } from "store/PhysicsStore";
import {
	ColorFade,
	CloseCar,
	OpenCar,
	ConvertibleDown,
	ConvertibleUp,
} from "lib/Utils";
import { useThree } from "@react-three/fiber";

const white = new Color(5, 5, 5);
const emissiveWhite = new Color(3, 3, 3);
const emissiveRed = new Color(5, 0, 0);
const red = new Color(3, 0, 0);

export function Model(props) {
	const { open, openRoof, color } = useDonutStore();

	const frunk = useRef();
	const roof = useRef();
	const rightDoor = useRef();
	const leftDoor = useRef();
	const roofInterior = useRef();
	const rightDoorGlass = useRef();
	const leftDoorGlass = useRef();
	const midTrunk = useRef();

	const { scene } = useThree();

	useEffect(() => {
		scene.traverse((nodes) => {
			if (nodes.isMesh && nodes.name.length === 0) {
				nodes.castShadow = true;
				nodes.material.envMapIntensity = 0.7;
			} else if (nodes.isMesh && nodes.name.length > 0) {
				nodes.material.envMapIntensity = 0;
				nodes.material.roughness = 0.8;
				nodes.material.metalness = 0.8;
			}
		});

		ColorFade(roof, color);
	}, [color]);

	useLayoutEffect(() => {
		if (open === false) {
			CloseCar(frunk, rightDoor, leftDoor, midTrunk);
		} else if (open === true) {
			OpenCar(frunk, rightDoor, leftDoor, midTrunk);
		}

		if (openRoof === false) {
			ConvertibleDown(roof, roofInterior, rightDoorGlass, leftDoorGlass);
		} else if (openRoof === true) {
			ConvertibleUp(roof, roofInterior, rightDoorGlass, leftDoorGlass);
		}
	}, [open, openRoof]);

	const { nodes, materials } = useGLTF(
		"/2019_chevrolet_corvette_c8_stingray-transformed.glb",
	);

	return (
		<group {...props} dispose={null}>
			<group scale={0.01}>
				<group
					position={[0, 71, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				>
					<mesh
						geometry={nodes.Main_Chassis_Body_Color_0.geometry}
						material={materials.Body_Color}
					/>
					<mesh
						geometry={nodes.Main_Chassis_Black_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Main_Chassis_Plastic_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={
							nodes.Main_Chassis_Invisible_Unimportant_Black_0
								.geometry
						}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Main_Chassis_Chrome_0.geometry}
						material={materials.Chrome}
					/>
					<mesh
						geometry={nodes.Main_Chassis_Painted_Black_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Main_Chassis_Mirror_0.geometry}
						material={materials.Mirror}
					/>
					<mesh
						geometry={nodes.Main_Chassis_Grille_6_0.geometry}
						material={materials.Grille_6}
					/>
					<mesh
						geometry={nodes.Main_Chassis_Grille_7_0.geometry}
						material={materials.Grille_7}
					/>
					<mesh
						geometry={nodes.Main_Chassis_Misc_0.geometry}
						material={materials.Misc}
					/>
					<mesh
						geometry={nodes.Corvette_Badge_Badges_0.geometry}
						material={materials.Badges}
					/>
					<mesh
						geometry={nodes.Headlights_Housing_Lights_0.geometry}
						material={materials.Lights}
					/>
					{/* long lights */}
					<mesh
						geometry={nodes.Day_Lights_Day_Lights_0.geometry}
						material={materials.Day_Lights}
					/>
					{/* headlights */}
					<mesh
						geometry={nodes.Headlights_Headlights_0.geometry}
						material={materials.Headlights}
						material-color={white}
						material-emissive={new Color(10, 10, 10)}
						material-toneMapped={false}
						material-emissiveIntensity={20}
					/>

					{/* TAILLIGHTS */}
					<mesh
						geometry={nodes.turnlight_r_Right_Indicator_0.geometry}
						material={materials.Day_Lights}
						material-color={white}
						material-emissive={emissiveWhite}
						material-emissiveIntensity={3}
						material-toneMapped={false}
					/>
					<mesh
						geometry={
							nodes.Right_Indicator_Left_Indicator_0.geometry
						}
						material={materials.Day_Lights}
						material-color={white}
						material-emissive={emissiveWhite}
						material-emissiveIntensity={10}
						material-toneMapped={false}
					/>
					<mesh
						geometry={nodes.Taillights_Taillights_0.geometry}
						material={materials.Day_Lights}
						material-color={red}
						material-emissive={emissiveRed}
						material-toneMapped={false}
					/>
					<mesh
						geometry={
							nodes.Reverse_Lights_Reverse_Lights_0.geometry
						}
						material={materials.Day_Lights}
						material-color={white}
						material-emissive={emissiveWhite}
						material-emissiveIntensity={3}
						material-toneMapped={false}
					/>
					<mesh
						geometry={nodes.Brake_Lights_Brake_Lights_0.geometry}
						material={materials.Day_Lights}
						material-color={red}
						material-emissiveColor={emissiveRed}
						material-emissiveIntensity={16}
					/>
					<mesh
						geometry={
							nodes.License_Plate_Lights_License_Plate_Lights_0
								.geometry
						}
						material={materials.License_Plate_Lights}
					/>
					<mesh
						geometry={nodes.SUSpension_Misc_0.geometry}
						material={materials.Misc}
					/>
					{/* roof */}
					<group>
						<mesh
							ref={roof}
							geometry={nodes.Roof_Body_Color_0.geometry}
							material={materials.Body_Color}
						/>
						<mesh
							ref={roofInterior}
							geometry={nodes.Roof_Interior_0.geometry}
							material={materials.Interior}
						/>
					</group>
					<mesh
						geometry={
							nodes[
								"62L_LT2_V8_Engine_and_Engine_Bay_Engine_Cover_0"
							].geometry
						}
						material={materials.Black}
					/>
					<mesh
						geometry={
							nodes[
								"62L_LT2_V8_Engine_and_Engine_Bay_Chrome_Engine_Pipes_Use_Grill_5_as_BW_to_Bump_to_Normal_0"
							].geometry
						}
						material={
							materials.Chrome_Engine_Pipes_Use_Grill_5_as_BW_to_Bump_to_Normal
						}
					/>
					<mesh
						geometry={
							nodes[
								"62L_LT2_V8_Engine_and_Engine_Bay_Engine_Decals_0"
							].geometry
						}
						material={materials.Engine_Decals}
					/>
					<mesh
						geometry={
							nodes.Engine_Bay_Bolts_Engine_Decals_0.geometry
						}
						material={materials.Engine_Decals}
					/>
					<mesh
						geometry={nodes.Grille1_Grille_1_0.geometry}
						material={materials.Grille_1}
					/>
					<mesh
						geometry={nodes.Grille1_Grille_3_0.geometry}
						material={materials.Grille_3}
					/>
					<mesh
						geometry={nodes.Grille1_Black_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Carbon_FIber_Carbon_Fiber_0.geometry}
						material={materials.Carbon_Fiber}
					/>
					<mesh
						geometry={nodes.Interior_Black_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Interior_Interior_Aluminium_0.geometry}
						material={materials.Interior_Aluminium}
					/>
					<mesh
						geometry={nodes.Interior_Plastic_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Interior_Grill_4_Speakers_0.geometry}
						material={materials.Grill_4_Speakers}
					/>
					<mesh
						geometry={nodes.Interior_Engine_Decals_0.geometry}
						material={materials.Engine_Decals}
					/>
					<mesh
						geometry={nodes.Interior_Interior_0.geometry}
						material={materials.Interior}
					/>
					<mesh
						geometry={nodes.Interior_Carpet_0.geometry}
						material={materials.Carpet}
					/>
					<mesh
						geometry={
							nodes
								.Interior_Seats_Adjust_the_leather_texture_using_Color_Ramp_or_using_HSV_0
								.geometry
						}
						material={
							materials.Seats_Adjust_the_leather_texture_using_Color_Ramp_or_using_HSV
						}
					/>
					<mesh
						geometry={nodes.Interior_Stitches_Interior_0.geometry}
						material={materials.Interior}
					/>
					<mesh
						geometry={
							nodes.Interior_Digitals_Interior_Buttons_0.geometry
						}
						material={materials.Interior_Buttons}
					/>
					<mesh
						geometry={nodes.Interior_Digitals_Gauges_0.geometry}
						material={materials.Gauges}
					/>
					<mesh
						geometry={
							nodes.Interior_Digitals_Interior_Display_0.geometry
						}
						material={materials.Interior_Display}
					/>
					<mesh
						geometry={nodes.Interior_Trim_Interior_Trim_0.geometry}
						material={materials.Interior_Trim}
					/>
					<mesh
						geometry={nodes.Interior_Trim_Badges_0.geometry}
						material={materials.Badges}
					/>
				</group>
				{/* frunk */}
				<group
					position={[-0.01, 89.11, -117.94]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					ref={frunk}
				>
					<mesh
						geometry={nodes.Frunk_Body_Color_0.geometry}
						material={materials.Body_Color}
					/>
					<mesh
						geometry={nodes.Frunk_Plastic_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Frunk_Bolt_2_Interior_0.geometry}
						material={materials.License_Plate_Lights}
					/>
				</group>
				<group
					position={[0, 107.66, -32.53]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				>
					<mesh
						geometry={nodes.Glasses_Windshield_0.geometry}
						material={materials.Windshield}
					/>
					<mesh
						geometry={
							nodes.Glasses_Other_Glasses_than_Windshield_0
								.geometry
						}
						material={materials.Other_Glasses_than_Windshield}
					/>
				</group>
				<group
					position={[93.3, 37.4, -144.8]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				>
					<mesh
						geometry={
							nodes.Front_Right_Wheel_Painted_Black_0.geometry
						}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Front_Right_Wheel_Brake_Disc_0.geometry}
						material={materials.Brake_Disc}
					/>
					<mesh
						geometry={
							nodes.Front_Right_Wheel_Tire_Treads_0.geometry
						}
						material={materials.Tire_Treads}
					/>
					<mesh
						geometry={
							nodes.Front_Right_Wheel_Tire_Sidewall_0.geometry
						}
						material={materials.Tire_Sidewall}
					/>
					<mesh
						geometry={nodes.Front_Right_Wheel_Rim_0.geometry}
						material={materials.material}
					/>
				</group>
				<group
					position={[-93.3, 37.4, -144.8]}
					rotation={[-Math.PI / 2, 0, -Math.PI]}
					scale={100}
				>
					<mesh
						geometry={
							nodes.Front_Left_Wheel_Painted_Black_0.geometry
						}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Front_Left_Wheel_Brake_Disc_0.geometry}
						material={materials.Brake_Disc}
					/>
					<mesh
						geometry={nodes.Front_Left_Wheel_Tire_Treads_0.geometry}
						material={materials.Tire_Treads}
					/>
					<mesh
						geometry={
							nodes.Front_Left_Wheel_Tire_Sidewall_0.geometry
						}
						material={materials.Tire_Sidewall}
					/>
					<mesh
						geometry={nodes.Front_Left_Wheel_Rim_0.geometry}
						material={materials.material}
					/>
				</group>
				<group
					position={[93, 39.25, 163.33]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={[100, 105, 105]}
				>
					<mesh
						geometry={
							nodes.Rear_Right_Wheel_Painted_Black_0.geometry
						}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Rear_Right_Wheel_Brake_Disc_0.geometry}
						material={materials.Brake_Disc}
					/>
					<mesh
						geometry={nodes.Rear_Right_Wheel_Tire_Treads_0.geometry}
						material={materials.Tire_Treads}
					/>
					<mesh
						geometry={
							nodes.Rear_Right_Wheel_Tire_Sidewall_0.geometry
						}
						material={materials.Tire_Sidewall}
					/>
					<mesh
						geometry={nodes.Rear_Right_Wheel_Rim_0.geometry}
						material={materials.material}
					/>
				</group>
				<group
					position={[-93, 39.14, 163.22]}
					rotation={[-Math.PI / 2, 0, -Math.PI]}
					scale={[100, 105, 105]}
				>
					<mesh
						geometry={
							nodes.Rear_Left_Wheel_Painted_Black_0.geometry
						}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Rear_Left_Wheel_Brake_Disc_0.geometry}
						material={materials.Brake_Disc}
					/>
					<mesh
						geometry={nodes.Rear_Left_Wheel_Tire_Treads_0.geometry}
						material={materials.Tire_Treads}
					/>
					<mesh
						geometry={
							nodes.Rear_Left_Wheel_Tire_Sidewall_0.geometry
						}
						material={materials.Tire_Sidewall}
					/>
					<mesh
						geometry={nodes.Rear_Left_Wheel_Rim_0.geometry}
						material={materials.material}
					/>
				</group>
				{/* right door */}
				<group
					ref={rightDoor}
					position={[96.28, 60.5, -86.52]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				>
					<mesh
						geometry={nodes.Right_Door_Body_Color_0.geometry}
						material={materials.Body_Color}
					/>
					<mesh
						geometry={nodes.Right_Door_Black_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Right_Door_Plastic_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Right_Door_Aluminium_0.geometry}
						material={materials.Aluminium}
					/>
					<mesh
						geometry={nodes.Right_Door_Painted_Black_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Right_Door_Mirror_0.geometry}
						material={materials.Mirror}
					/>
					<mesh
						geometry={nodes.Right_Door_Grill_4_Speakers_0.geometry}
						material={materials.Grill_4_Speakers}
					/>
					<mesh
						geometry={nodes.Right_Door_Interior_Trim_2_0.geometry}
						material={materials.Interior_Trim_2}
					/>
					<mesh
						geometry={nodes.Right_Door_Engine_Decals_0.geometry}
						material={materials.Engine_Decals}
					/>
					<mesh
						geometry={nodes.Right_Door_Interior_0.geometry}
						material={materials.Interior}
					/>
					<mesh
						geometry={nodes.Right_Door_Interior_Buttons_0.geometry}
						material={materials.Interior_Buttons}
					/>
					{/* right window */}
					<mesh
						ref={rightDoorGlass}
						geometry={
							nodes
								.Right_Door_Glass_Other_Glasses_than_Windshield_0
								.geometry
						}
						material={materials.Other_Glasses_than_Windshield}
					/>
					<mesh
						geometry={nodes.Right_Door_Stitches_Interior_0.geometry}
						material={materials.Interior}
					/>
					<mesh
						geometry={
							nodes.Right_Indicator_Mirror_Right_Indicator_0
								.geometry
						}
						material={materials.Day_Lights}
					/>
				</group>
				{/* left door */}
				<group
					ref={leftDoor}
					position={[-96.2, 60.6, -86.5]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				>
					<mesh
						geometry={nodes.Left_Door_Body_Color_0.geometry}
						material={materials.Body_Color}
					/>
					<mesh
						geometry={nodes.Left_Door_Black_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Left_Door_Plastic_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Left_Door_Aluminium_0.geometry}
						material={materials.Aluminium}
					/>
					<mesh
						geometry={nodes.Left_Door_Painted_Black_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Left_Door_Mirror_0.geometry}
						material={materials.Mirror}
					/>
					<mesh
						geometry={nodes.Left_Door_Grill_4_Speakers_0.geometry}
						material={materials.Grill_4_Speakers}
					/>
					<mesh
						geometry={nodes.Left_Door_Interior_Trim_2_0.geometry}
						material={materials.Interior_Trim_2}
					/>
					<mesh
						geometry={nodes.Left_Door_Engine_Decals_0.geometry}
						material={materials.Engine_Decals}
					/>
					<mesh
						geometry={nodes.Left_Door_Interior_0.geometry}
						material={materials.Interior}
					/>
					<mesh
						geometry={nodes.Left_Door_Interior_Buttons_0.geometry}
						material={materials.Interior_Buttons}
					/>
					<mesh
						geometry={
							nodes.Left_Indicator_Mirror_Left_Indicator_0
								.geometry
						}
						material={materials.Day_Lights}
					/>
					<mesh
						ref={leftDoorGlass}
						geometry={
							nodes
								.Left_Door_Glass_Other_Glasses_than_Windshield_0
								.geometry
						}
						material={materials.Other_Glasses_than_Windshield}
					/>
					<mesh
						geometry={nodes.Left_Door_Stitches_Interior_0.geometry}
						material={materials.Interior}
					/>
				</group>
				{/* Trunk */}
				<group
					ref={midTrunk}
					position={[0, 126.6, 69.86]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				>
					<mesh
						geometry={nodes.Trunk_or_Hood_Body_Color_0.geometry}
						material={materials.Body_Color}
					/>
					<mesh
						geometry={nodes.Trunk_or_Hood_Black_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={nodes.Trunk_or_Hood_Plastic_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={
							nodes.Trunk_Glass_Dark_Engine_View_Glass_0.geometry
						}
						material={materials.Dark_Engine_View_Glass}
					/>
					<mesh
						geometry={nodes.Trunk_Glass_Grille_7_0.geometry}
						material={materials.Grille_7}
					/>
					<mesh
						geometry={nodes.Trunk_Glass_Badges_0.geometry}
						material={materials.Badges}
					/>
				</group>
				<group
					position={[-40.17, 76.98, -46.4]}
					rotation={[-1.82, 0, 0]}
					scale={100}
				>
					<mesh
						geometry={nodes.Steering_Wheel_Black_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={
							nodes.Steering_Wheel_Interior_Aluminium_0.geometry
						}
						material={materials.Interior_Aluminium}
					/>
					<mesh
						geometry={nodes.Steering_Wheel_Interior_0.geometry}
						material={materials.Interior}
					/>
					<mesh
						geometry={
							nodes.Steering_Wheel_Decals_Interior_0.geometry
						}
						material={materials.Interior}
					/>
					<mesh
						geometry={
							nodes.Steering_Wheel_Decals_Interior_Badge_0
								.geometry
						}
						material={materials.Interior_Badge}
					/>
				</group>
				<group
					position={[99.48, 70.81, 187.43]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				>
					<mesh
						geometry={nodes.License_Plate_Plastic_0.geometry}
						material={materials.Black}
					/>
					<mesh
						geometry={
							nodes.License_Plate_License_Plate_Background_0
								.geometry
						}
						material={materials.License_Plate_Background}
					/>
					<mesh
						geometry={nodes.License_Plate_License_Plate_0.geometry}
						material={materials.License_Plate}
					/>
				</group>
				<mesh
					geometry={nodes.Front_Right_Brake_Caliper_Misc_2_0.geometry}
					material={materials.Misc_2}
					position={[93.3, 37.4, -144.8]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.Front_Left_Brake_Caliper_Misc_2_0.geometry}
					material={materials.Misc_2}
					position={[-93.3, 37.5, -144.7]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.Speedo_Needle_Mat_supergt209_0.geometry}
					material={materials["Mat_supergt.209"]}
					position={[-40.14, 85.45, -68.47]}
					rotation={[-1.71, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.Right_WIper_Black_0.geometry}
					material={materials.Black}
					position={[-14.41, 83.51, -142.91]}
					rotation={[-0.54, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.Left_Wiper_Black_0.geometry}
					material={materials.Black}
					position={[-72.85, 81.17, -125.06]}
					rotation={[-0.56, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.Rear_Left_Brake_Caliper_Misc_0.geometry}
					material={materials.Misc}
					position={[-93, 39.14, 163.22]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.Rear_Right_Brake_Caliper_Misc_0.geometry}
					material={materials.Misc}
					position={[93, 39.24, 163.32]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/2019_chevrolet_corvette_c8_stingray-transformed.glb");
